### PR TITLE
support params ordered

### PR DESCRIPTION
**Pull request by twz915**
see https://github.com/tiaguinho/gosoap/issues/53

### CODE REVIEW

**Comment by tiaguinho** [comment]
Thank you for the PR @twz915.
Can you take a look at the tests? The changes you have done has decreased by more than 2% of the coverage we have.

**Comment by twz915** [comment]
@codecov-io test again?

**Comment by xhit** [comment]
I tested the change and the coverage increase a ~2% and PR works like a charm. Unfortunelly Codecov don't update in github the coverage, @tiaguinho should see the Codecov link instead.

I like this change, I will be using it in my project until it is merged. Thanks @twz915

**Comment by l3uddz** [comment]
Works perfectly.

Thanks @twz915

**Pull request merged**
