### PR TITLE
Enable dumping http request/response for better debugging V2

### PR DESCRIPTION
**Pull request by mhewedy**
A replqcement for #42

### CODE REVIEW

**Comment by tiaguinho** [comment]
[Enable dumping http request/response for better debugging V2](https://trello.com/c/YJMLDGpQ/9-enable-dumping-http-request-response-for-better-debugging-v2)

**Comment by tiaguinho** [comment]
Thanks for the PR.

Can you please fix the tests?

**Comment by insomniacslk** [comment]
@mhewedy , thanks for this PR, i was looking for this too :) Any plan to fix and merge it?

**Comment by mhewedy** [comment]
Conflicts fixed, could you please merge @tiaguinho

**Pull request merged**
