### PR TITLE
Include details into FaultError String repr

### PR DESCRIPTION
**Pull request by requiemofthesouls**

### CODE REVIEW

**Comment by tiaguinho** [comment]
Thanks for your contribution @requiemofthesouls .
Can you fix the tests?

**Comment by requiemofthesouls** [comment]
alright, I'll try

**Comment by requiemofthesouls** [comment]
@tiaguinho Done, but seems we lost $COVERALLS_TOKEN environment. It fails on second CI job.

**Comment by tiaguinho** [comment]
No problem @requiemofthesouls 

Thank you for your contribution.

**Pull request merged**
